export const ADD_PLAYLIST='ADD_PLAYLIST'
export const UPDATA_SCREEN='UPDATA_SCREEN'
export const UPDATA_PLAYING='UPDATA_PLAYING'
export const UPDATA_PLAYING_BOOL='UPDATA_PLAYING_BOOL'
export const UPDATA_CURRENTINDEX='UPDATA_CURRENTINDEX'
export const UPDATA_MODE='UPDATA_MODE'
export const RANDOM_LIST='RANDOM_LIST'
export const UPDATA_SEQUENCE='RANDOM_SEQUENCE'
export const CHANGE_SONGLIST='CHANGE_SONGLIST'
export const DELETE_SONG='DELETE_SONG'


